import { useEffect, useState } from "react";
import { Link, useRoute } from "wouter";
import { ArrowLeft, ArrowUpRight, Check, CircleAlert, FileText, LockKeyhole, MessageSquare, ShieldCheck, Sparkles } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { CaseStatusBadge } from "@/components/case/case-status-badge";
import { RiskIndicator } from "@/components/case/risk-indicator";
import { ConfidenceIndicator } from "@/components/intelligence/confidence-indicator";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { mockCaseService } from "@/services/case-service";
import { caseCategoryLabels, type CaseDetail, type CaseRoomTab } from "@/types/vindicai";

const tabs: { value: CaseRoomTab; label: string; deferred?: boolean }[] = [{ value: "info", label: "Case info" }, { value: "timeline", label: "Timeline", deferred: true }, { value: "evidence", label: "Evidence", deferred: true }, { value: "research", label: "Research", deferred: true }, { value: "intelligence", label: "Intelligence" }, { value: "strategy", label: "Strategy", deferred: true }, { value: "drafts", label: "Drafts", deferred: true }, { value: "actions", label: "Actions", deferred: true }];
export default function CaseRoom() {
  const [, params] = useRoute("/cases/:id"); const [detail, setDetail] = useState<CaseDetail>(); const [tab, setTab] = useState<CaseRoomTab>("info");
  useEffect(() => { if (params?.id) mockCaseService.getCase(params.id).then((result) => setDetail(result.data)); }, [params?.id]);
  if (!detail) return <AppShell><div className="container py-20 text-center"><p className="text-sm text-muted-foreground">Loading case record...</p></div></AppShell>;
  return <AppShell><div className="container pb-16 pt-7 sm:pt-9"><Link href="/cases" className="text-xs text-muted-foreground hover:text-foreground"><ArrowLeft className="mr-1 inline size-3.5" /> Case index</Link><header className="mt-6 rounded-lg border border-border bg-card p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-muted-foreground"><span>{detail.id}</span><span>·</span><span>{detail.category ? caseCategoryLabels[detail.category] : "Dispute"}</span></div><h1 className="mt-3 max-w-3xl font-display text-3xl tracking-[-0.035em] sm:text-4xl">{detail.title}</h1><p className="mt-2 text-sm text-muted-foreground">{detail.counterparty} · {detail.amount} · Opened {detail.openedAt}</p></div><div className="flex flex-wrap items-center gap-2"><CaseStatusBadge status={detail.status} /><RiskIndicator level={detail.risk} /><Button className="gap-2 bg-primary" onClick={() => toast.success("Approval packet prepared", { description: "The case is ready for a human owner to review before any action is sent." })}><LockKeyhole className="size-4" /> Request approval</Button></div></div><div className="mt-7 grid gap-4 border-t border-border pt-5 sm:grid-cols-4"><Info label="Owner" value={detail.owner} /><Info label="Last activity" value={detail.lastActivity} /><Info label="Sources" value={`${detail.evidenceCount} indexed`} /><Info label="AI confidence" value={`${detail.confidence}%`} /></div></header><div className="mt-5 overflow-x-auto border-b border-border"><div className="flex min-w-max gap-1" role="tablist" aria-label="Case Room sections">{tabs.map((item) => item.deferred ? <Link key={item.value} href={`/cases/${detail.id}/${item.value}`} className="border-b-2 border-transparent px-3 py-3 text-xs font-semibold text-muted-foreground transition-colors hover:border-primary hover:text-foreground">{item.label}<span className="ml-1 text-[9px] font-normal opacity-60">↗</span></Link> : <button key={item.value} role="tab" aria-selected={tab === item.value} onClick={() => setTab(item.value)} className={`border-b-2 px-3 py-3 text-xs font-semibold transition-colors ${tab === item.value ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"}`}>{item.label}</button>)}</div></div><div className="mt-6">{tab === "info" && <InfoPanel detail={detail} />}{tab === "intelligence" && <IntelligencePanel detail={detail} />}{tab === "strategy" && <StrategyPanel detail={detail} />}{tab === "drafts" && <DraftsPanel detail={detail} />}{tab === "actions" && <ActionsPanel detail={detail} />}</div></div></AppShell>;
}
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] font-bold uppercase tracking-[0.13em] text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>; }
function Panel({ eyebrow, title, children, tone = "default" }: { eyebrow?: string; title: string; children: React.ReactNode; tone?: "default" | "sage" | "amber" }) { return <section className={`rounded-md border p-5 sm:p-6 ${tone === "sage" ? "border-[#cfdcca] bg-[#f1f6ef]" : tone === "amber" ? "border-[#e8d7b9] bg-[#fbf5e9]" : "border-border bg-card"}`}><div className="flex items-start justify-between gap-4"><div>{eyebrow && <p className="text-[10px] font-bold uppercase tracking-[0.15em] text-muted-foreground">{eyebrow}</p>}<h2 className="mt-1 text-base font-semibold">{title}</h2></div></div><div className="mt-5">{children}</div></section>; }
function InfoPanel({ detail }: { detail: CaseDetail }) { return <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_340px]"><div className="space-y-5"><Panel eyebrow="What happened" title="Issue summary"><p className="text-sm leading-7 text-muted-foreground">{detail.description}</p><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-md bg-[#f5f1e8] px-2.5 py-1.5 text-xs font-semibold text-[#8f7349]">Desired outcome</span><span className="rounded-md border border-border px-2.5 py-1.5 text-xs">{detail.desiredOutcome}</span></div></Panel><Panel eyebrow="Verified record" title="Facts we can stand behind"><div className="space-y-3">{detail.verifiedFacts.map((fact) => <div key={fact} className="flex gap-3"><span className="mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full bg-[#dbe9d9] text-[#55755d]"><Check className="size-3" /></span><p className="text-sm leading-6">{fact}</p></div>)}</div></Panel></div><div className="space-y-5"><Panel eyebrow="Open questions" title="Still needs context" tone="amber"><div className="space-y-3">{detail.openQuestions.map((question) => <div key={question} className="flex gap-3"><CircleAlert className="mt-0.5 size-4 shrink-0 text-[#a17a43]" /><p className="text-xs leading-5 text-muted-foreground">{question}</p></div>)}</div></Panel><Panel eyebrow="Case path" title="Milestones"><div className="space-y-4">{detail.milestones.map((milestone) => <div key={milestone.label} className="flex gap-3"><span className={`mt-1 size-2 shrink-0 rounded-full ${milestone.state === "verified" ? "bg-[#6f9478]" : milestone.state === "review" ? "bg-[#b58a52]" : "bg-[#9aa39d]"}`} /><div><p className="text-xs font-semibold">{milestone.label}</p><p className="mt-1 text-[11px] text-muted-foreground">{milestone.detail}</p></div></div>)}</div></Panel></div></div>; }
function IntelligencePanel({ detail }: { detail: CaseDetail }) { return <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_340px]"><Panel eyebrow="AI recommendation" title="A reviewable next step" tone="sage"><div className="flex gap-4"><span className="flex size-10 shrink-0 items-center justify-center rounded-md bg-[#dbe9d9] text-[#55755d]"><Sparkles className="size-5" /></span><div><p className="text-base leading-7 text-foreground">{detail.aiRecommendation}</p><div className="mt-4 flex items-center gap-3"><ConfidenceIndicator value={detail.confidence} /><span className="text-xs text-muted-foreground">based on {detail.evidenceCount} indexed sources</span></div></div></div></Panel><Panel eyebrow="Fact confidence" title="Verified vs unverified"><div className="space-y-4">{detail.claims.map((claim) => <div key={claim.label} className="border-b border-border/70 pb-4 last:border-0 last:pb-0"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold">{claim.label}</p><span className={`text-[10px] font-bold uppercase tracking-[0.1em] ${claim.state === "verified" ? "text-[#55755d]" : "text-[#a17a43]"}`}>{claim.state}</span></div><p className="mt-1 text-xs leading-5 text-muted-foreground">{claim.detail}</p></div>)}</div></Panel></div>; }
function StrategyPanel({ detail }: { detail: CaseDetail }) { return <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_340px]"><Panel eyebrow="Recommended strategy" title="Protect the record before the negotiation"><div className="rounded-md bg-[#f5f1e8] p-4"><p className="text-sm font-semibold">Lead with the verified facts.</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Keep unverified causes separate from the requested remedy, and make the next approval explicit.</p></div><div className="mt-5 space-y-4"><div className="flex gap-3"><ShieldCheck className="size-4 text-[#55755d]" /><div><p className="text-xs font-semibold">Anchor on source-backed facts</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Use the matched statements and contract language as the opening position.</p></div></div><div className="flex gap-3"><MessageSquare className="size-4 text-[#6b8594]" /><div><p className="text-xs font-semibold">Keep the ask narrow</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Request the correction first; reserve the causal question for follow-up.</p></div></div></div></Panel><Panel eyebrow="Decision guardrails" title="Before you act"><ul className="space-y-3 text-xs text-muted-foreground"><li>• Confirm the account owner has seen the draft.</li><li>• Preserve the two statements as the primary sources.</li><li>• Do not imply migration causality until verified.</li></ul></Panel></div>; }
function DraftsPanel({ detail }: { detail: CaseDetail }) { return <Panel eyebrow="Prepared outputs" title="Drafts ready for review"><div className="grid gap-3 sm:grid-cols-2">{detail.drafts.map((draft) => <div key={draft.title} className="rounded-md border border-border bg-background p-4"><div className="flex items-start justify-between gap-3"><FileText className="size-4 text-[#5c7890]" /><span className="text-[10px] font-bold uppercase tracking-[0.1em] text-muted-foreground">{draft.state}</span></div><p className="mt-4 text-sm font-semibold">{draft.title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{draft.detail}</p><Button variant="link" size="sm" className="mt-3 h-auto gap-1 p-0 text-xs">Open draft <ArrowUpRight className="size-3" /></Button></div>)}</div></Panel>; }
function ActionsPanel({ detail }: { detail: CaseDetail }) { return <Panel eyebrow="Human-controlled actions" title="Next actions"><div className="space-y-3">{detail.nextActions.map((action) => <div key={action.label} className="flex flex-col gap-3 rounded-md border border-border bg-background p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><p className="text-sm font-semibold">{action.label}</p><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold uppercase tracking-[0.08em] ${action.state === "approval" ? "bg-[#f7ead9] text-[#976d38]" : "bg-[#e4eee5] text-[#55755d]"}`}>{action.state}</span></div><p className="mt-1 text-xs text-muted-foreground">{action.detail} · Owner: {action.owner}</p></div><Button variant="outline" size="sm" onClick={() => toast.info("Review queue updated", { description: `${action.label} remains human-controlled and is ready for owner review.` })}>Review</Button></div>)}</div></Panel>; }
function DeferredPanel({ label }: { label: string }) { return <div className="rounded-md border border-dashed border-border bg-card px-6 py-16 text-center"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-muted-foreground">Step 9+</p><h2 className="mt-2 text-lg font-semibold">{label} is next</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">This Case Room tab is intentionally reserved for the next build. The current workspace keeps the decision context visible without pretending the feature is complete.</p></div>; }
