import { useEffect, useMemo, useState } from "react";
import { Link, useRoute } from "wouter";
import { ArrowUpRight, BookOpen, CalendarDays, ChevronRight, ExternalLink, Scale, Search, ShieldAlert, Sparkles } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { FlipText } from "@/components/shared/flip-text";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { mockIntelligenceService } from "@/services/intelligence-service";
import type { IntelligenceKind, ResearchResult, ResearchStatus } from "@/mocks/intelligence";

const kindMeta: Record<IntelligenceKind, { icon: typeof BookOpen; tone: string }> = { Fact: { icon: ShieldAlert, tone: "text-[#55755d] bg-[#e4eee5]" }, Policy: { icon: BookOpen, tone: "text-[#8f7349] bg-[#f5f1e8]" }, "Law / Rule": { icon: Scale, tone: "text-[#5c7890] bg-[#e8eef2]" }, "AI Inference": { icon: Sparkles, tone: "text-[#976d38] bg-[#f7ead9]" } };
const statusTone: Record<ResearchStatus, string> = { VALID: "text-[#55755d] bg-[#e4eee5]", STALE: "text-[#8f7349] bg-[#f5f1e8]", CONFLICTED: "text-[#a4584c] bg-[#f8e7e2]", "REQUIRES REVIEW": "text-[#976d38] bg-[#f7ead9]" };
export default function ResearchCenter() {
  const [items, setItems] = useState<ResearchResult[]>([]); const [query, setQuery] = useState(""); const [kind, setKind] = useState("all"); const [selected, setSelected] = useState<ResearchResult>();
  const [, params] = useRoute("/cases/:id/research");
  useEffect(() => { mockIntelligenceService.getResearch(params?.id).then(({ data }) => { setItems(data); setSelected(data[0]); }); }, [params?.id]);
  const filtered = useMemo(() => items.filter((item) => `${item.title} ${item.source} ${item.authority}`.toLowerCase().includes(query.toLowerCase()) && (kind === "all" || item.kind === kind)), [items, query, kind]);
  return <AppShell><div className="container pb-16 pt-8 sm:pt-10"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-muted-foreground">Step 11 · Context layer</p><h1 className="mt-2 font-display text-4xl tracking-[-0.035em]">Research center</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Pull policy, rule, and source context into the case without flattening facts, inference, and authority into one answer.</p></div><Button asChild variant="outline" className="w-fit gap-2"><a href="/policies">Open policy intelligence <ArrowUpRight className="size-4" /></a></Button></div><section className="mt-8 grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]"><div className="rounded-md border border-border bg-card"><div className="flex flex-col gap-3 border-b border-border p-4 lg:flex-row"><label className="flex flex-1 items-center gap-2 rounded-md border border-border bg-background px-3 py-2"><Search className="size-4 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} className="h-5 border-0 bg-transparent p-0 text-sm shadow-none focus-visible:ring-0" placeholder="Search research and citations" aria-label="Search research" /></label><select className="h-9 rounded-md border border-border bg-background px-3 text-xs" value={kind} onChange={(event) => setKind(event.target.value)} aria-label="Filter by research type"><option value="all">All types</option><option value="Fact">Fact</option><option value="Policy">Policy</option><option value="Law / Rule">Law / Rule</option><option value="AI Inference">AI Inference</option></select></div><div className="divide-y divide-border/80">{filtered.map((item) => { const meta = kindMeta[item.kind]; const Icon = meta.icon; return <button key={item.id} onClick={() => setSelected(item)} className={`flex w-full items-start gap-3 p-4 text-left hover:bg-[#faf9f5] ${selected?.id === item.id ? "bg-[#f7faf5]" : ""}`}><span className={`flex size-9 shrink-0 items-center justify-center rounded-md ${meta.tone}`}><Icon className="size-4" /></span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold">{item.title}</span><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${statusTone[item.status]}`}><FlipText text={item.status} /></span></span><span className="mt-1 block text-xs text-muted-foreground">{item.source} · {item.authority}</span><span className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-[10px] uppercase tracking-[0.1em] text-muted-foreground"><span>Effective {item.effectiveDate}</span><span>Confidence {item.confidence}%</span></span></span><ChevronRight className="mt-1 size-4 shrink-0 text-muted-foreground" /></button>; })}</div></div>{selected && <ResearchDetail item={selected} />}</section></div></AppShell>;
}
function ResearchDetail({ item }: { item: ResearchResult }) { const Icon = kindMeta[item.kind].icon; return <aside className="space-y-5"><section className="rounded-md border border-border bg-card p-5"><div className="flex items-start justify-between gap-3"><span className={`flex size-9 items-center justify-center rounded-md ${kindMeta[item.kind].tone}`}><Icon className="size-4" /></span><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${statusTone[item.status]}`}><FlipText text={item.status} /></span></div><h2 className="mt-5 text-lg font-semibold leading-6">{item.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{item.detail}</p><div className="mt-5 grid grid-cols-2 gap-4 border-y border-border py-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.13em] text-muted-foreground">Authority</p><p className="mt-1 text-xs font-semibold">{item.authority}</p></div><div><p className="text-[10px] font-bold uppercase tracking-[0.13em] text-muted-foreground">Effective</p><p className="mt-1 text-xs font-semibold">{item.effectiveDate}</p></div></div><div className="mt-4 flex items-center justify-between"><span className="text-xs text-muted-foreground">Confidence signal</span><span className="text-sm font-bold text-[#55755d]">{item.confidence}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#e7e4dc]"><div className="h-full rounded-full bg-[#7c9c82] transition-all duration-500" style={{ width: `${item.confidence}%` }} /></div></section><section className="rounded-md border border-border bg-card p-5"><div className="flex items-center gap-2"><CalendarDays className="size-4 text-muted-foreground" /><h2 className="text-sm font-semibold">Citations</h2></div><div className="mt-4 space-y-2">{item.citations.map((citation) => <div key={citation} className="flex items-center justify-between rounded-md bg-[#f7f5ef] px-3 py-2.5 text-xs"><span>{citation}</span><ExternalLink className="size-3.5 text-muted-foreground" /></div>)}</div><Button asChild variant="link" size="sm" className="mt-3 gap-1 px-0 text-xs"><Link href="/evidence">Open evidence explorer <ArrowUpRight className="size-3" /></Link></Button></section></aside>; }
