import { AlertTriangle, CheckCircle2, CloudOff, LoaderCircle, RefreshCcw, ShieldAlert, Sparkles } from "lucide-react";
import { AnimatePresence, motion } from "framer-motion";
import type { ReactNode } from "react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { useReducedMotion } from "@/hooks/use-reduced-motion";
import { Button } from "@/components/ui/button";

export function PageTransition({ children }: { children: ReactNode }) { const [location] = useLocation(); const reduced = useReducedMotion(); return <AnimatePresence mode="wait"><motion.div key={location} initial={reduced ? false : { opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={reduced ? undefined : { opacity: 0, y: -6 }} transition={{ duration: .22, ease: [0.23, 1, 0.32, 1] }}>{children}</motion.div></AnimatePresence>; }

export function OfflineBanner() { const [online, setOnline] = useState(() => typeof navigator === "undefined" ? true : navigator.onLine); const [restored, setRestored] = useState(false); useEffect(() => { const offline = () => { setOnline(false); setRestored(false); }; const onlineAgain = () => { setOnline(true); setRestored(true); window.setTimeout(() => setRestored(false), 4000); }; window.addEventListener("offline", offline); window.addEventListener("online", onlineAgain); return () => { window.removeEventListener("offline", offline); window.removeEventListener("online", onlineAgain); }; }, []); return <AnimatePresence>{(!online || restored) && <motion.div initial={{ opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }} className={`border-b px-4 py-2 text-center text-xs font-semibold ${online ? "border-[#b8cdb8] bg-[#f1f6ef] text-[#55755d]" : "border-[#ead9ba] bg-[#fbf5e9] text-[#976d38]"}`} role="status">{online ? <span className="inline-flex items-center gap-2"><CheckCircle2 className="size-3.5" />Connection restored. Mock workspace is ready.</span> : <span className="inline-flex items-center gap-2"><CloudOff className="size-3.5" />You are offline. Changes are not being saved; reconnect before consequential actions.</span>}</motion.div>}</AnimatePresence>; }

const processingCopy: Record<string, { label: string; detail: string }> = { Analyzing: { label: "Analyzing", detail: "Comparing source context" }, Researching: { label: "Researching", detail: "Mapping applicable policy" }, Verifying: { label: "Verifying", detail: "Checking provenance" }, "Checking Contradictions": { label: "Checking contradictions", detail: "Testing claims against the record" }, "Checking Freshness": { label: "Checking freshness", detail: "Reviewing source dates" }, "Preparing Strategy": { label: "Preparing strategy", detail: "Organizing defensible next moves" }, "Awaiting Approval": { label: "Awaiting approval", detail: "A human decision is required" } };
export function AIProcessingIndicator({ state, compact = false }: { state: keyof typeof processingCopy; compact?: boolean }) { const reduced = useReducedMotion(); const copy = processingCopy[state]; return <div className={`ai-processing ${compact ? "ai-processing-compact" : ""}`} role="status" aria-live="polite"><span className="ai-processing-icon">{state === "Awaiting Approval" ? <ShieldAlert className="size-4" /> : <Sparkles className={`size-4 ${reduced ? "" : "ai-processing-spark"}`} />}</span><span><strong>{copy.label}</strong>{!compact && <span className="ai-processing-detail">{copy.detail}</span>}</span>{state !== "Awaiting Approval" && <span className="ai-processing-dots" aria-hidden="true"><i /><i /><i /></span>}</div>; }

export function EmptyState({ title, detail, action, onAction }: { title: string; detail: string; action?: string; onAction?: () => void }) { return <div className="empty-state"><span className="empty-state-icon"><Sparkles className="size-5" /></span><h2>{title}</h2><p>{detail}</p>{action && onAction && <Button variant="outline" className="mt-5 gap-2" onClick={onAction}>{action}<RefreshCcw className="size-3.5" /></Button>}</div>; }
export function PermissionDenied({ area = "this workspace surface" }: { area?: string }) { return <div className="empty-state"><span className="empty-state-icon warning"><ShieldAlert className="size-5" /></span><h2>Access needs approval</h2><p>Your role does not currently include access to {area}. Ask a workspace admin to review your permissions.</p></div>; }
export function ErrorStateCard({ title = "We couldn't load this record", detail = "The mock service returned an error. Try again; nothing was marked as saved.", onRetry }: { title?: string; detail?: string; onRetry?: () => void }) { return <div className="rounded-lg border border-[#ead1cb] bg-[#fdf5f2] p-5" role="alert"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 size-5 shrink-0 text-[#a84e43]" /><div><h2 className="text-sm font-semibold text-[#8f3d35]">{title}</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">{detail}</p>{onRetry && <Button variant="outline" className="mt-4 gap-2 border-[#d4aaa2] text-[#8f3d35]" onClick={onRetry}><RefreshCcw className="size-3.5" />Try again</Button>}</div></div></div>; }
export function SkeletonBlock({ className = "" }: { className?: string }) { return <div className={`skeleton-block ${className}`} aria-hidden="true"><LoaderCircle className="size-4" /></div>; }

export function ProcessingFailure({ onRetry, onReview }: { onRetry?: () => void; onReview?: () => void }) { return <div className="rounded-lg border border-[#ead1cb] bg-[#fdf5f2] p-5" role="alert"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 size-5 shrink-0 text-[#a84e43]" /><div><p className="text-sm font-semibold text-[#8f3d35]">Analysis could not be completed.</p><p className="mt-1 text-xs leading-5 text-muted-foreground"><strong>Reason:</strong> source verification failed for one or more records.</p><p className="mt-1 text-xs leading-5 text-muted-foreground"><strong>Impact:</strong> no recommendation or draft was marked ready.</p><div className="mt-4 flex flex-wrap gap-2">{onRetry && <Button className="gap-2 bg-[#8f3d35] text-white hover:bg-[#74312b]" onClick={onRetry}><RefreshCcw className="size-3.5" />Retry analysis</Button>}{onReview && <Button variant="outline" onClick={onReview}>Review evidence</Button>}</div></div></div></div>; }
export function ActionFailure({ onRetry, onReview }: { onRetry?: () => void; onReview?: () => void }) { return <div className="rounded-lg border border-[#ead9ba] bg-[#fbf5e9] p-5" role="alert"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 size-5 shrink-0 text-[#976d38]" /><div><p className="text-sm font-semibold text-[#7f5b2e]">Action was not executed.</p><p className="mt-1 text-xs leading-5 text-muted-foreground"><strong>Reason:</strong> approval or integration readiness could not be confirmed.</p><p className="mt-1 text-xs leading-5 text-muted-foreground"><strong>Impact:</strong> no external message, change, or submission was made.</p><div className="mt-4 flex flex-wrap gap-2">{onRetry && <Button variant="outline" className="gap-2 border-[#d9c39f] text-[#7f5b2e]" onClick={onRetry}><RefreshCcw className="size-3.5" />Check again</Button>}{onReview && <Button variant="outline" onClick={onReview}>Review approval</Button>}</div></div></div></div>; }
